remote_theme: techie-joe/core
# the location of the remote_theme.

title: Core template
description: Core is a classless website template.
nickname: Core
# title: # the title of your site (best without the punctuation dot).
# description: # a short description of your site's purpose.
# nickname: # a shortname for your site.

show_downloads: true # true or false (unquoted).
# indicate whether to provide a download URL.

# google_analytics: # your Google Analytics tracking ID.
# to track your website using Google Analytics.

# github:
  # zip_url: http://example.com/download.zip
  # another_url: another_value

theme_color: '#222'
color_scheme: light dark

sass:
  style: compressed

# plugins:
# - jekyll-paginate
# - jekyll-sitemap

exclude: # exclude these files from production site.
- ".editorconfig"
- ".github"
- ".gitignore"
- node_modules
- script
- ".sass-cache"
- ".jekyll-cache"
- ".jekyll-metadata"
- "*.gem"
- "*.gemspec"
- Gemfile
- Gemfile.lock
- ".bundle"
- vendor
- CNAME
- "*.ignore"
- ".backup"
- ".localhost"