remote_theme: techie-joe/core
# the location of the remote_theme.

# plugins:
# - jekyll-paginate
# - jekyll-sitemap

title: Core
description: Core is a Jekyll theme for GitHub Pages.
# title: # the title of your site (best without the punctuation dot).
# description: # a short description of your site's purpose.

# google_analytics: # your Google Analytics tracking ID.
# to track your website using Google Analytics.

# show_downloads: # true or false (unquoted).
# indicate whether to provide a download URL.

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another_value

theme_color: '#222'
color_scheme: light dark

sass:
  style: compressed

# exclude these files from Jekyll production site (_site).
exclude:
- ".editorconfig"
- ".github"
- ".gitignore"
- ".sass-cache"
- ".jekyll-cache"
- ".jekyll-metadata"
- "*.gem"
- "*.gemspec"
- Gemfile
- Gemfile.lock
- ".bundle"
- vendor
- script
- node_modules
- package-lock.json
- package.json
- gulpfile.js
- gulplist.js
- site
- CNAME
- "*.ignore"
- ".backup"
- ".localhost"